apiVersion: apps/v1
kind: Deployment
metadata:
  name: svcctl
spec:
  replicas: 1
  selector:
    matchLabels:
      name: svcctl
  template:
    metadata:
      labels:
        name: svcctl
    spec:
      serviceAccountName: svcctl
      containers:
        - name: svcctl
          # Replace this with the built image name
          image: metaswitchglobal.azurecr.io/plw/svcctl-operator:latest
          command:
          - svcctl
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "svcctl"
